=== jj98-trabajo/primer/custom_addons/material_needs/security/ir.rule.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="odoo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="data">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="record">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="field" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="name" use="required" />
                                                        <xs:attribute name="ref" />
                                                        <xs:attribute name="eval" />
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" use="required" />
                                    <xs:attribute name="model" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="noupdate" type="xs:integer" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== jj98-trabajo/primer/custom_addons/material_needs/security/ir.rule.xml
<odoo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="ir.rule.xsd">
    <data noupdate="1">
        <record id="material_needs_rule_by_functional_area" model="ir.rule">
            <field name="name">Restricción por área funcional</field>
            <field name="model_id" ref="model_material_needs_material_needs"/>
            <field name="domain_force">[('functional_area_id', 'in', user.functional_area_ids.ids)]</field>
            <field name="groups" eval="[(4, ref('base.group_user'))]"/>
            <field name="perm_read" eval="True"/>
        </record>
    </data>
</odoo>
